[env:esp32-c3-devkitm-1]
platform = espressif32
platform_packages =
    framework-arduinoespressif32 @ symlink://C:/Users/wangs/AppData/Local/Arduino15/packages/esp32/hardware/esp32/2.0.12
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
upload_speed = 921600
build_src_filter =
    +<*>
    -<diagnostics/>
    -<AircraftManager.cpp>
    -<ConfigurationWebServer.cpp>
    -<DrawHelpers.cpp>
    -<HttpRequestManager.cpp>
    -<OpenSkyAuthTokenHandler.cpp>
    -<models/>
build_unflags =
    -std=gnu++11
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DASTRONOMY_ENGINE_WHOLE_SECOND
    -std=gnu++17
    -Wall
board_build.flash_mode = dio
board_build.partitions = huge_app.csv

[env:factory-display-diagnostic]
extends = env:esp32-c3-devkitm-1
build_src_filter =
    -<*>
    +<diagnostics/display_diagnostic.cpp>
